NickMcConnell/NarSil

- src/mon-move.c
Resolves https://github.com/NickMcConnell/NarSil/issues/153 .
> Fix bad indexing of ddgrid_ddd in get_move_retreat()/get_move_wander()

- src/mon-group.c
Resolves https://github.com/NickMcConnell/NarSil/issues/179 .
> Avoid use after free in monster_remove_from_group()

- src/ui-abilities.c
- src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/185 .
> Don't pass a string from the datafiles to text_out_c()'s format argument

- src/player-calcs.c
Resolves https://github.com/NickMcConnell/NarSil/issues/198
> update_bonuses(): update player state before propagating knowledge

- src/gen-cave.c
Were suppressed entirely by dcea3e1648599aab8d0b5deff08ac6a157c682b7 .
> Restore room-to-corridor tunnels

- src/ui-death.c
Was done from both death_knowledge() and death_screen().
> Don't enter the score twice at death

- src/project-feat.c
Resolves the Staff of Freedom part of https://github.com/NickMcConnell/NarSil/issues/90 .
> Fix KILL_DOOR projection

- src/mon-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/211 .
> Avoid infinite loops in choose_ranged_attack()

- src/cmd-obj.c
Resolves https://github.com/NickMcConnell/NarSil/issues/218 .
> Avoid crash when putting on a shield with no weapon equipped

- lib/gamedata/terrain.txt
Resolves https://github.com/NickMcConnell/NarSil/issues/216 .
> Drop WALL terrain flag for rubble

- lib/gamedata/history.txt
Resolves https://github.com/NickMcConnell/NarSil/issues/224 .
> Insert space for Naugrim and Edain histories

- src/obj-info.c
Resolves https://github.com/NickMcConnell/NarSil/issues/227 . For future-proofing (not relevant to matching Sil), generalize the abilities listed for an object to allow for a not fully identified object that has a known kind or ego with abilities.
> Limit displayed brands or slays for an object to what's known

- src/save.c
Resolves https://github.com/NickMcConnell/NarSil/issues/228 (for all savefiles written after the change).
> Replace "L0" in savefile's description with player's total experience

- src/cave-square.c
- src/cmd-cave.c
Fixes regression introduced by e53929fac8e8950d6a815716168085a90a6ee9fc .
> Make rubble diggable

- src/cmd-cave.c
Resolves https://github.com/NickMcConnell/NarSil/issues/233 .
This has overlapping changes with https://github.com/NickMcConnell/NarSil/pull/231 .  If you want to apply both, apply whichever one you want to be first and I can fix up the conflicts for the other.
> Do not leak information about a secret door by tunneling or altering

- src/obj-pile.c
Resolves https://github.com/NickMcConnell/NarSil/issues/235 .
> Prevent weapons and armor of different weight from combining

- src/ui-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/239 .
> Smithing numbers menu: update after selection made

- src/player-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/241 .
> Avoid use after free in ranged_helper()

- src/player-abilities.c
- src/ui-player.c
Resolves https://github.com/NickMcConnell/NarSil/issues/243 .
> Have sidebar/character sheet update immediately when player selects ability

- src/mon-util.c
Resolves https://github.com/NickMcConnell/NarSil/issues/249 .
> Set damage source to the chasm's grid for monsters falling into chasms

- src/cmd-obj.c
Resolves https://github.com/NickMcConnell/NarSil/issues/251 .
> Handle pack overflow when wielding

- src/cmd-obj.c
Resolves some of the horn issues from https://github.com/NickMcConnell/NarSil/issues/90 .
> Using a horn uses voice and stops your song

- src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/257 .
> Birth: have screen correctly reflect selection after using '*' for the house

- src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/256 .
> Birth: remove finish with random choices option

- src/player-abilities.c
Resolves https://github.com/NickMcConnell/NarSil/issues/260 .
> Fix test for ability if it is in multiple skill trees

- src/mon-blows.c
Resolves https://github.com/NickMcConnell/NarSil/issues/222 .
> Check for player's resistance to poisoned blows

- src/mon-move.c
Takes care of part of https://github.com/NickMcConnell/NarSil/issues/177 .
> Get correct range for scouts and spies

- src/mon-msg.c
That's to match melee2.c:3393-3398 in Sil 1.3.
> Add noise/chance to wake for monster's warning shouts

- lib/gamedata/object.txt
- lib/gamedata/projection.txt
- src/cmd-obj.c
- src/effect-handler-attack.c
- src/effects.c
- src/list-effects.h
- src/obj-util.c
- src/obj-util.h
- src/project-feat.c
Resolves the last of the horn-related issues mentioned so far in https://github.com/NickMcConnell/NarSil/issues/90 .
> Get horns of blasting to work

- src/player-util.c
Resolves https://github.com/NickMcConnell/NarSil/issues/277 .
> Have rest as needed wait for voice to be restored as well

- src/ui-command.c
Resolves https://github.com/NickMcConnell/NarSil/issues/279 .
> Prompt before exiting with control-x while in the tutorial

- src/game-world.c
- src/mon-move.c
That's to better match Sil 1.3
> Adjust monster pathfinding so closed doors are not treated like walls

- lib/gamedata/constants.txt
Addresses one cause for https://github.com/NickMcConnell/NarSil/issues/286 .
> Match Sil 1.3's maximum mana for monsters

- lib/gamedata/monster_spell.txt
- src/mon-init.c
Resolves https://github.com/NickMcConnell/NarSil/issues/286 (if https://github.com/NickMcConnell/NarSil/pull/288 is also applied).
> Set default maximum range for monster spells to z_info->max_range

- src/mon-attack.c
- src/mon-spell.c
Mindless monsters cast randomly from a minimally pruned set of spells.  Fast spell selection uses the pruned set of spells.  Also somewhat optimize remove_bad_spells() (avoid extra copying of the spell flags, only consider spells that are on in the set).
> Better match Sil 1.3's monster spell selection

- src/project-player.c
Resolves https://github.com/NickMcConnell/NarSil/issues/291 .
> Signal combat before setting breath damage rolls

- src/project.c
Resolves https://github.com/NickMcConnell/NarSil/issues/293 .  Also updates the description of project()'s arguments.
> Match Sil 1.3 for the damage of breath weapons

- src/cmd-obj.c
- src/obj-gear.c
Check for merging of quiver stacks in combine_pack().  Resolves https://github.com/NickMcConnell/NarSil/issues/296 .  Move weight limit check from inven_carry_okay() to inven_carry_num() so it can be imposed when picking up more than one object from a stack.   Update test in inven_carry_num() for how the number that can go to the quiver is calculated.  When wielding ammunition, prefer to merge with an already occupied quiver slot and enforce the weight limit.  In do_cmd_wield(), only combine the pack if picking up from the floor to avoid the possibility of a dangling reference if the object taken off combines with the object to be wielded.
> Tweak handling of gear

- src/obj-make.c
- src/obj-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/303 .
> Smithing: for ego, add minimum bonus, 1; match Sil 1.3's att_max()/att_min()

- src/mon-blows.c
Resolves https://github.com/NickMcConnell/NarSil/issues/309 .
> Account for player's protection in blow handlers using monster_damage_target()

- src/ui-skills.c
Resolves https://github.com/NickMcConnell/NarSil/issues/308 .
> Undo any selections made when escaping from skills selection

- src/list-options.h
Resolves https://github.com/NickMcConnell/NarSil/issues/287 .
> Have "pickup if in inventory" option be off by default

- src/ui-score.c
Resolves https://github.com/NickMcConnell/NarSil/issues/160 .  Also flattens the response loop for displaying scores.
> Score display: change the prompt displayed if full scrolling is not allowed

- src/player-util.c
Likely resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of searching being more difficult than expected.
> Match Sil 1.3's penalty for searching at a distance

- src/trap.c
Resolves https://github.com/NickMcConnell/NarSil/issues/248 .
> Trap: skip extra effect or other side effects if player is dead

- src/mon-attack.c
That matches Sil 1.3.  Resolves https://github.com/NickMcConnell/NarSil/issues/371 .
> Monster's cruel blow: always give message and confusion

- src/player-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/374
> Remember that a monster ripostes if seen in action

- src/player-calcs.c
- src/player.h
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 : "Song of Staying doesn't raise armor, at least not on the ui. It does buff will."
> For PU_BONUS, trigger redraw if protection roll bounds change

- src/ui-abilities.c
That better matches Sil 1.3 and resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161524&postcount=39 : "Checking the Bane ability doesn't say how many monsters of a given type you've killed, nor what the current bonus is."
> If Bane has been learned, show type and details in the abilities menu

- src/effect-handler-attack.c
- src/project.c
- src/project.h
Resolves part of wobbly's report here, http://angband.oook.cz/forum/showpost.php?p=161597&postcount=40
> Limit breath effect visuals to where damage can be inflicted

- lib/gamedata/monster_spell.txt
- src/mon-init.c
Resolves https://github.com/NickMcConnell/NarSil/issues/400
> Set empty messages in monster_spell.txt for songs

- lib/gamedata/object_property.txt
Resolves https://github.com/NickMcConnell/NarSil/issues/411 .
> Mention the LIGHT flag, if present, when an object is examined

- src/datafile.c
- src/main-stats.c
Affects saving the randart file and main-stats.c.
> Be consistent with the list of modifier names

- src/ui-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/413 .
> Color entries in smithing's enchant menu by affordability

- src/gen-util.c
- src/obj-make.c
Resolves https://github.com/NickMcConnell/NarSil/issues/433 .
> Fix logic and comments for place_object()/make_object()'s drop argument

- src/mon-make.c
Resolves https://github.com/NickMcConnell/NarSil/issues/432 .
> Fix typo in place_monster_by_letter()

- src/mon-make.c
Noticed by Karcharoth.  Introduced in https://github.com/NickMcConnell/NarSil/pull/442 .
> Fix typo introduced when fixing place_monster_by_letter()

- src/ui-display.c
Resolves https://github.com/NickMcConnell/NarSil/issues/451 .
> Change where update_maps() is unregistered

- src/mon-move.c
See Sil 1.3's melee2.c:868.  May affect https://github.com/NickMcConnell/NarSil/issues/361 .
> Include non-sleeping monsters in group's furthest wandering distance

- src/mon-group.c
Better matches Sil 1.3:  see cmd1.c:52-53.
> Wander to stairs if empty in addition to if there's a monster there

- src/cmd-misc.c
Resolves https://github.com/NickMcConnell/NarSil/issues/448 .
> Trigger mini screenshot upon escaping Angband

- src/cmd-cave.c
Resolves https://github.com/NickMcConnell/NarSil/issues/462 .
> Apply stricter conditions for walking out of the Gates

- src/gen-cave.c
Resolves https://github.com/NickMcConnell/NarSil/issues/464 .
> Make Gates level large enough for permanent boundary at top

- src/cmd-pickup.c
Resolves https://github.com/NickMcConnell/NarSil/issues/467 .
> Avoid use after free in pickup_aux()

- src/gen-cave.c
See Sil 1.3's generate.c:1283-1284.
> Impose Sil 1.3's limit on the vertical part of bent tunnels

- src/gen-room.c
> Match Sil 1.3's doubled wall check for the left walls

- src/gen-room.c
See Sil 1.3's gen-room.c:2071-2077
> Distinguish 4th subtype of crossed room to match Sil 1.3

- src/gen-cave.c
- src/gen-util.c
- src/generate.c
- src/generate.h
Resolves https://github.com/NickMcConnell/NarSil/issues/475 .
> Allow greater vaults on failed levels to be generated on other levels

- src/gen-room.c
Resolves https://github.com/NickMcConnell/NarSil/issues/474 .
> Limit greater vaults to one per level like Sil 1.3

- src/gen-room.c
> Match Sil 1.3's test for a doubled wall on the right side

- src/gen-room.c
- src/generate.c
- src/generate.h
Resolves https://github.com/NickMcConnell/NarSil/issues/486 .
> Use vault rarity

- src/gen-cave.c
See Sil 1.3's generate.c:1604.
> Match Sil 1.3's chance for more rubble on deep levels

- src/main-cocoa.m
- src/obj-tval.c
- src/object.h
- src/wiz-stats.c
- src/z-file.c
* Correct types, repeated words, and some other nonsense in comments.
* Another fix for a nonsensical comment.
> Correct types, repeated words, and some other nonsense in comments. (#5523)

- src/source.c
Don't partially initialize a struct using a braced initializer.
> source: placate compiler

- src/ui-target.c
Original changes are from Vanilla Angband's 6f0c45eeb7101b1cc79db0ce721734342351fcb3 and 496fc1c51d5276100d924c5a64ca1585f676c205.  They were made by Daniel Burgener, burgener.daniel@gmail.com, and Eric Branlund, ebranlund@fastmail.com.
> Port Vanilla Angband's changes for targeting messages while blind

- src/ui-options.c
Resolves https://github.com/angband/angband/issues/5322 .
> Add borders around option menu prompts that don't clear the screen

- src/effect-handler-attack.c
That's so all other messages appear before "You die." if the player is killed.
> Port Vanilla Angband's change to damage player last in an earthquake

- src/player-timed.c
Resolves https://github.com/NickMcConnell/NarSil/issues/565 .
> Correct stunning's blackout threshold in player_set_timed()

- src/obj-util.c
Resolves https://github.com/NickMcConnell/NarSil/issues/567 .
> Avoid using NULL dice expressions in obj_nourishes()

- src/mon-init.c
Avoid memory leaks in cases of parser errors or multiple dice lines for the same spell.  Use PARSE_ERROR_MISSING_RECORD_HEADER for cases where other lines appear before any spell name rather than a mixture of PARSE_ERROR_MISSING_RECORD_HEADER and assertions.
> Port Vanilla Angband's changes to parsing for monster_spell.txt

- src/ui-display.c
Avoids duplicating thresholds/labels/colors from player_timed.txt in prt_cut() and prt_poisoned().
> Use player_timed.txt's configuration for sidebar display of cuts/poison

- lib/gamedata/monster.txt
- src/main-sdl2.c
- src/main.c
> typos found by Debian lintian (#5680)

- src/ui-display.c
Resolves https://github.com/angband/angband/issues/5743
> Separate repeat/rest info on status line from what follows

- src/ui-mon-lore.c
Resolves https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781748 .
> For spoilers, use full set of flags rather than those currently in lore

- src/ui-object.c
- src/ui-options.c
- src/ui-player.c
- src/wiz-spoil.c
Resolves https://github.com/NickMcConnell/FAangband/issues/397 (also present in vanilla).
> Handle padding of text that could contain multibyte UTF-8 characters

- m4/buildsys.m4
- mk/buildsys.mk.in
- mk/extra.mk.in
The new option to configure, --disable-silent-rules, may be useful for diagnosing problems in the build process.
> Merge in buildsys's upstream changes as of 2023/09/10

- src/main-nds.c
Resolves https://github.com/angband/angband/issues/5810 .
> Add solid/hybrid wall support for Nintendo front end

- docs/customize.rst
That's a response to smbhax's post here, http://angband.oook.cz/forum/showpost.php?p=161295&postcount=6 .
> Docs: mention the toggle ignore command in the ignoring section

- src/ui-input.c
Those are for handling split point corner cases and to slightly optimize finding the split point.
> Port Vanilla Angband's changes to "-more-" prompts

- src/mon-init.c
That matches what NarSil uses.
> Cap number of pain messages per type at 3

- src/main-sdl2.c
Also provide clearer diagnostics if there is trouble with lib/fonts.  See http://angband.oook.cz/forum/showpost.php?p=161635&postcount=14 and the posts after it for some discussion.
> SDL2: more robustly handle unusable configured font

- src/cave-view.c
Reverts change made in 2019, https://github.com/angband/angband/commit/ab3fad0966e256ae25ac43f0c404f6c250af83f2 .  Resolves agoodman's report here, https://angband.live/forums/forum/angband/vanilla/248821-spear-of-light#post248821 .
> Allow glowing terrain that's not in a room or on the surface to light a wall

- lib/gamedata/flavor.txt
- lib/tiles/microchasm/flvr-mcm.prf
Resolves https://github.com/NickMcConnell/NarSil/issues/733 .
> Drop the flavors used in Sil for Easter eggs

- src/mon-make.c
- src/mon-move.c
- src/obj-make.c
- src/player-abilities.c
- src/ui-display.c
The only substantive error was for the use of the uninitialized variable in mon-move.c.
> Squash errors and one warning with msbuild

- src/init.c
- src/init.h
- src/mon-move.c
- src/tests/parse/z-info.c
Resolves the second and third parts of https://github.com/NickMcConnell/NarSil/issues/735 .
> Store some monster-related constants as uint8_t

- src/target.c
Resolves https://github.com/NickMcConnell/NarSil/issues/753 .
> Have object previously seen be interesting when looking

- src/tutorial.c
Resolves https://github.com/NickMcConnell/NarSil/issues/754 .
> Handle player's version of the cave in the tutorial

- src/player-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/759 .
> Learn brand/slay/flag before tallying player's hit of a monster

- src/mon-lore.c
Resolves https://github.com/NickMcConnell/NarSil/issues/764 .
> Correct writing lore when there is more than one known drop

- src/player-calcs.c
Resolves https://github.com/NickMcConnell/NarSil/issues/774 .
> Properly handle main hand empty and off-hand with weapon in calc_bonuses()

- src/player-calcs.c
Resolves https://github.com/NickMcConnell/NarSil/issues/774 .
> Properly handle main hand empty and off-hand with weapon in calc_bonuses() (1.3)

- src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/773 .
> Prevent multiple birth stat display handlers from being registered

- src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/773 .
> Prevent multiple birth stat display handlers from being registered (1.3 branch)

- src/obj-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/798 .
> Touch completed smithed object

- src/cave-map.c
Resolves https://github.com/NickMcConnell/NarSil/issues/800 .
> For map, test base object, not known version, for glowing

- src/cave-map.c
Resolves https://github.com/NickMcConnell/NarSil/issues/816 .
> Correct forgetting of objects when a Mewlip rings its bell

- src/obj-smith.c
> Automatically combine result of melting mithril item with existing stack

- src/obj-smith.c
> Automatically combine result of melting mithril item with existing stack - 1.3

- src/obj-smith.c
1) Account for a mithril stack in the pack that might combine with the result of melting the item.
2) Use the max_stack relevant for pieces of mithril.  Prior calculation used a mix of max_stack for the item to melt and max_stack for pieces of mithril.  No effect currently as max_stack is the same for both.
> Tweak needed slots calculation for melting mithril item

- src/obj-desc.c
- src/ui-object.c
Resolves https://github.com/NickMcConnell/NarSil/issues/853 .
> Set up known object for recall subwindow's kind recall

- src/ui-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/850 .
> Properly handle resuming interrupted smithing away from a forge

- src/ui-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/850 for the 1.3 branch.
> Properly handle resuming interrupted smithing away from a forge - 1.3

- src/obj-ignore.c
Ported from Vanilla where it resolved https://github.com/angband/angband/issues/6169 .
> Same autoinscription when aware or unaware: do not unnecessarily reinscribe

- src/main-x11.c
Seen with clang 16.0.6 on OpenBSD.
> Avoid set but unused warnings - 1.3

- docs/customize.rst
Resolves https://github.com/angband/angband/issues/6243 .  Also describe how that window<->subwindow relationship is managed.
> Fix missing word in the documentation about configuring SDL2

- src/project-mon.c
Resolves https://github.com/NickMcConnell/NarSil/issues/919 .
> Correct damage rolls for projections affecting monsters

- src/cave-square.c
- src/cmd-pickup.c
- src/datafile.c
- src/game-input.c
- src/player-birth.c
- src/player-timed.c
- src/player-util.c
- src/ui-map.c
- src/ui-term.c
- src/ui-visuals.c
- src/z-color.c
- src/z-dict.c
- src/z-file.c
The one that remains is about not locating an include file for an unit test case and is also present in Vanilla.
> Resolve almost all of the the remaining warnings from doxygen

- src/option.c
- src/option.h
- src/ui-options.c
Scroll those shown as necessary.  Resolves https://github.com/angband/angband/issues/6367 .
> Remove limit on number of options shown per category - 1.3
