src/cmd-wizard.c, src/game-world.c, src/init.c, src/mon-attack.c, src/mon-make.c, src/obj-chest.c, src/obj-init.c, src/obj-pile.c, src/obj-smith.c, src/player-abilities.c, src/player-abilities.h, src/player-timed.c, src/player.c, src/songs.c, src/trap.c, src/ui-smith.c
Resolves all of the leaks reported in https://github.com/NickMcConnell/NarSil/issues/164 except for the one caused by the multiple dice directives in object.txt for the horn of blasting.
=> Plug memory leaks detected when running the tutorial

src/ui-display.c, src/ui-score.c
Avoids deprecation warnings with clang 14.0.0 on macOS 12.6.5.
=> Replace sprintf() with strnfmt()

src/mon-attack.c
Potential for crash was introduced by f7f0e27a2c984fe679bbef302eda0e2803a6aed4 .  Resolves https://github.com/NickMcConnell/NarSil/issues/192 .
=> Avoid crash due to erroneous free in make_attack_normal()

src/gen-cave.c
Avoids some of the dead ends contributing to https://github.com/NickMcConnell/NarSil/issues/68 .
=> Fix dead ends in corridors generated by connect_room_to_corridor()

src/gen-cave.c, src/gen-util.c, src/generate.h
Now can allocate more than one object (was passing the number of objects as the depth) and the origin is properly set by callers.  Helps address MITZE's and Bill Peterson's reports here, http://angband.oook.cz/forum/showpost.php?p=160610&postcount=59 , and here, http://angband.oook.cz/forum/showpost.php?p=160628&postcount=60 .
The number of floor objects and rubble may still need tweaking to match Sil 1.3: alloc_object() here will only fail to allocate the requested number if the number of grids in the dungeon matching the placement criteria is less than the requested number of objects while Sil 1.3's version has a stochastic chance of failure to place an object.
=> Better match Sil 1.3's alloc_object()

lib/gamedata/object.txt
Resolves https://github.com/NickMcConnell/NarSil/issues/164 .  Has no effect on the horn issues in https://github.com/NickMcConnell/NarSil/issues/90 (horns of blasting use the BEAM effect which does not affect terrain; horns don't interrupt singing and don't cost voice when successfully used).
=> Plug memory leaks parsing the horns of thunder and blasting

src/cmd-obj.c, src/obj-gear.c, src/obj-gear.h, src/obj-util.c, src/player-attack.c
The removing part matches what Sil 1.3 allows.  Resolves https://github.com/NickMcConnell/NarSil/issues/60 .  The throwing part is an extension since NarSil allows throwing the equipped weapon but Sil 1.3 does not.
=> Allow Curse Breaking for removing and throwing besides dropping

src/player-birth.c, src/player-calcs.c, src/ui-birth.c, src/ui-player.c
Resolves https://github.com/NickMcConnell/NarSil/issues/181 and https://github.com/NickMcConnell/NarSil/issues/124 .  Moves hack for pre-birth stat calculations from ui-player.c to player-calcs.c so the melee, defense, hp, voice, and skill calculations are correct as well.  Differs from Sil 1.3 in that backing out from the stat buy screen retains the current selections from that screen:  that's for consistency with backing out of the other choices where the last choice made is remembered.
=> Fix birth display issues

src/player-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/232 .
May want to check if Sil 1.3's behavior should be adopted of not being able to target the player's grid or to see if there's something, perhaps in repeating the last command or targeting the most recent target which has since died or moved out of sight, which causes the target to be the player's grid when the player isn't expecting that.  For the latter, that may have a tie to https://github.com/NickMcConnell/NarSil/issues/201 .
=> Protect ranged_helper() against undefined behavior if target is self

src/gen-cave.c, src/gen-room.c
Use SQUARE_WALL_INNER for '#' in vaults.  Resolves https://github.com/NickMcConnell/NarSil/issues/245 . '%' is for quartz in vaults.
Prevent streamers from changing secret doors.  That's another cause for https://github.com/NickMcConnell/NarSil/issues/68 and for disconnecting the internals of vaults. Change code comments to match what is done and to flag potential issues with the tunneling, both in NarSil and Sil 1.3.
=> Change terrain use during generation to better match Sil 1.3

src/player-timed.c
Resolves part of https://github.com/NickMcConnell/NarSil/issues/90 : stat potions have awkward messaging when they lapse.
=> Timed stat boosts do not require special handling when ending

src/effect-handler-general.c
In other words, the effect did happen, but may have done nothing.  A staff of sanctity will now be marked as {tried} when used without a cursed item equipped.  That's part of https://github.com/NickMcConnell/NarSil/issues/90 .
=> Have REMOVE_CURSE effect handler always return true

src/ui-display.c
Resolves https://github.com/NickMcConnell/NarSil/issues/201 .
Sil 1.3 clears both the morale and health lines when the monster is unseen/imagined/dead (see health_redraw() in xtra1.c), but in case there's some value for showing the player a difference between no health_who and an unseen/imagined/dead monster in health_who, keep NarSil's current handling for the health bar of unseen/imagined/dead monsters.
=> Do not display morale for unseen/imagined/dead monster

lib/gamedata/object.txt, src/effect-handler-general.c
Resolves the part of https://github.com/NickMcConnell/NarSil/issues/90 related to lack of messages for the staff of warding.  Also adds a commented out message for the staff of self knowledge to match what's in Sil 1.3's code for it.
=> Better match Sil 1.3's messaging for the staff of warding

src/project-mon.c
Previous logic differed from Sil 1.3's spells1.c:2694-2716.
=> Alert monsters affected by projected fear

lib/gamedata/object.txt, src/effect-handler-general.c, src/player-timed.c, src/player-timed.h
Addresses part of https://github.com/NickMcConnell/NarSil/issues/90 .
While this matches Sil 1.3's behavior for those herbs, it feels like unnecessary frustration for the player since NarSil displays a % full indicator on the status line:  if the player watches that indicator he or she can see that the herb has an effect even if the grade doesn't change. If you do want to apply this as is, I'd also make the change that only the name of the grade for TMD_FOOD is shown on the status bar.
=> Only ID herbs of sustenance and emptiness if the grade for TMD_FOOD changes

src/cave-square.c
That fixes a regression introduced by https://github.com/NickMcConnell/NarSil/commit/e53929fac8e8950d6a815716168085a90a6ee9fc .
=> Have square_iswall() return true for rubble

src/game-world.c
Because square_iswall() returns true for closed/secret doors, noise propagation was stopping at them.
=> Have noise propagate through closed doors

src/game-world.c
Avoids accessing illegal grids and unnecessary computation.
=> Reorder statments in update_flow()

src/ui-output.c
Fixes an assertion reported in https://github.com/NickMcConnell/NarSil/issues/16 while displaying the throne room poem.
=> Only signal that the map is visible if cave is not NULL

src/ui-display.c
That's for consistency with how the herbs of sustenance and emptiness are only identified if the grade for TMD_FOOD changes.
=> Drop the percent full indicator on the status line

lib/gamedata/monster_spell.txt, src/mon-spell.c
Resolves https://github.com/NickMcConnell/NarSil/issues/299 .  Also add protection in spell_message() for cases where a spell does not specify a message for the seen or unseen case.
=> Like Sil, use the same message for the SLOW monster spell if seen or unseen

src/ui-combat.c
Resolves https://github.com/NickMcConnell/NarSil/issues/311 .
For chest traps, Sil 1.3 sets the character and attribute for the combat rolls window to be what's used for the chest (see cmd2.c:703-704).  To emulate that in NarSil, would need to get the struct object pointer for the chest in to update_combat_rolls().  One way would to that would be for struct source to store both a chest_trap and object pointer for SRC_CHEST_TRAP (and update source_chest_trap() to support setting both).  That is not done here.
=> Combat rolls: limit use of race pointers to players and visible monsters

src/cmd-obj.c, src/obj-knowledge.c, src/player-attack.c
Resolves https://github.com/NickMcConnell/NarSil/issues/316 .  Refactors thrown_potion_effects() to use the player argument passed to ranged_helper() rather than the player global.
=> Object messages: add an article or number before a full name when needed

src/ui-input.c
Gets the keymaps for ',' and '^Z' to work as expected for altering the player's current grid.
=> textui_get_rep_dir(): honor allow_5 when processing a queued direction

src/combat.c
As a macro, MIN() can evaluate its arguments more than once leading to incorrect results if those arguments can change (for example, if an argument includes a call to a random number generator) between evaluations.
=> Fix cursed skill checks

src/cmd-obj.c, src/obj-util.c
1) Increase the timeout rather than replace the timeout with that of the fuel source.
2) Reverse logic for skipping fueling from a flask if it would waste fuel.
3) Allow the use command for flasks if the character has a lantern equipped.
Resolves Bill Peterson's report here, http://angband.oook.cz/forum/showpost.php?p=161407&postcount=4 .
=> Fix refueling lanterns

src/project-mon.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , for use ID not working for staffs of slumber.
=> For sleep/confusion/slow/speed effects, obvious if target seen and affected

src/obj-make.c
That's to match Sil 1.3 and resolve Infinitum's report, http://angband.oook.cz/forum/showpost.php?p=161417&postcount=6 , that a staff of sanctity did not work with a cursed amulet of constitution.
=> Mark cursed jewellery with OBJ_NOTICE_CURSED and OBJ_NOTICE_BROKEN

src/mon-make.c
That's to better match Sil 1.3 and resolve Infinitum's report here, http://angband.oook.cz/forum/showthread.php?t=11559 , that staffs of summoning are identified by use even if the effect is not seen.
=> pick_and_place_monster_on_stairs(): only return true if seen

src/ui-birth.c
Resolves https://github.com/NickMcConnell/NarSil/issues/337 .
=> free_birth_menu(): set menu_data to NULL to avoid downstream double frees

src/obj-smith.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , that a ring of sustenance costs one strength to smith.  Also corrects the strength needed to smith (Vampiric) items.
=> Use smith-cost set by object_property.txt

src/ui-smith.c
1) In the sval menu, reevaluate the cost of smithing the base item to set the shading rather than reuse whatever is in current_cost.
2) For the top level menu, clear the flags on the Numbers, Melt, and Accept entries if the conditions for use are met.  For the Melt entry, tighten the conditions to include the presence of a forge with at least one use to match what Sil 1.3 does.
Should resolve Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of wonkiness with the highlighting constructible items in the smithing menus.
=> Correct some shading issues in the smithing menus

src/cmd-obj.c, src/obj-util.c
Like Sil 1.3, using a torch or lantern will prefer to tap it as a fuel source, if there is a similar light source equipped, rather than equipping it.  Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of not being able to use an item to equip it.
=> Allow the use command to equip an unequipped wearable item

src/mon-summon.c
That's to match Sil 1.3 rather than the Angband calculation which averages it with the player's depth and then boosts that result by 5.  Should resolve Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of an overly deadly roost with a Shadow Spider.
=> In summon_specific() use requested level as is

src/obj-util.c, src/obj-util.h, src/player-attack.c, src/ui-context.c
Ported from Angband.  Which items can be thrown remains as it was in NarSil 1.3 though that is different than Sil 1.3.
=> Only show the "Throw" context menu option for objects that can be thrown

lib/gamedata/tutorial.txt, src/cmd-cave.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of "Ctrl-movement key used to bash doors iirc?".
=> Have alter grid bash closed doors to match Sil 1.3

src/project-mon.c
monster_death() already calls delete_monster_idx() so another call to it is fatal.  Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 , of "Red serpent breathes fire, doesn't kill me, kills green serpent. Game crashes to desktop."
=> Fix duplicate delete_monster_idx() calls in death from monster's projection

src/cmd-obj.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 : "Attempting to wield a dagger of accompaniment in the offhand (without native TWF) causes CTD."
=> Prevent crashes when wielding into an empty off-hand weapon slot

src/ui-knowledge.c
Resolves part of Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 : "Whispering Shadows don't show up in the monster memory since there's no worm category. Could go under W'ights etc, lore is they're remnants of defeated Maiar from ages past. Also their lore blurb looks like a draft; "(...) sounds (voices?)(...)" could be replaced by just "voices" and flow better imo."
=> Have whispering shadows show up in the wight/wraight category

src/ui-display.c
Noticed while trying and failing to reproduce https://github.com/NickMcConnell/NarSil/issues/354 .
=> In sidebar, display timed stat indicator on the correct line

src/cmd-cave.c, src/trap.c, src/tutorial.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 : "Not getting a warning that pits cannot be disarmed when trying to ctrl-move into a pit."
=> Fix handling of undisarmable kinds of traps

lib/gamedata/tutorial.txt, src/tutorial-init.c, src/tutorial-init.h, src/tutorial.c
They are not used in the current tutorial's content and are missing logic in the main game's search code (and likely disarming code) to have them not be detected by searching and still be disarmable.
=> Remove tutorial's option for invisible traps

src/mon-lore.c
Possibly resolves https://github.com/NickMcConnell/NarSil/issues/350 .  Did see a crash when a green serpent was killed by a blow from the Opportunist skill:  in the lore update after the death, evaluating the expression for spell power tried to use cave_monster(cave, cave->mon_current)->race but that was NULL because the monster was dead.
=> When appending spells to monster lore, set ref_race for expressions

lib/gamedata/object.txt, src/effects.c
Were healing (max hp - curr hp) / 2.  Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161471&postcount=23 : "Unconfirmed, but Healing potions seem to heal less than I remember from Sil."
=> Healing potions: heal 1/2 of max HP as in Sil 1.3

src/mon-group.c, src/mon-msg.c, src/player-quest.c
Resolves https://github.com/NickMcConnell/NarSil/issues/375 .  May impact https://github.com/NickMcConnell/NarSil/issues/351 .  Where the centre was not set for monster's warning messages, also use NULL for the mon argument to update_flow() since the flow update is for noise rather than pathfinding.
=> Set centre for cases where it was not set before calling update_flow()

src/project-player.c
That matches Sil 1.3.  Resolves https://github.com/NickMcConnell/NarSil/issues/373 .
=> Monster's crippling shot: always give message and slowing

src/cave-map.c
Resolves https://github.com/NickMcConnell/NarSil/issues/362 : objects in view become invisible after a mewlip successfully rings its bell.
=> In wiz_dark(), mark grids as unseen so view calculations start from scratch

src/load.c, src/save.c
Resolves Infinitum's reports here http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 : "Upon closing the program and restoring a saved game, player seems to have forgotten a lot of known items? Especially weapon egos. Needs confirmation." and "Confirming that a lot of weapons egos drops out of knowledge after restoring the game. Re-Id'ing Nargothrond and whatnot. Get new xp for rediscovering. Not sure about other item types."
=> Record ego's aware flag when saving; restore it when loading

lib/gamedata/object.txt, src/obj-init.c
Resolves Infinitum's report here http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 :  "Grond lacks damage dice."
=> For instant artifact kinds, inherit flags and element info of the tval

src/obj-gear.c, src/player-abilities.c, src/player-abilities.h, src/tutorial.c, src/ui-abilities.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 , that taking Dexterity from the Evasion tree meant that the user interface stopped displaying the prequisites for Dexterity from the Stealth tree, as if it had already been taken.  Also, for coloring the prerequisity abilities, only use slate for the ones that are innate to match Sil 1.3 (see cmd4.c:1172).
=> Refactor player_has_ability() to test full ability rather than name

src/player-quest.c
The call also triggers a use after free if the second Silmaril was pried out while the first was in the inventory (the second combines with the first causing memory referenced by sil in prise_silmaril() to be freed).  May resolve Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 , of a crash after prying out the second Silmaril.
=> Don't call object_desc() for a Silmaril:  result is unused

src/player-util.c, src/player-util.h, src/ui-abilities.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161397&postcount=2 : "Some buggy menuing trying to gain the bane ability. Texts not formatted properly, cannot choose a category and the game allows the player to choose bane without specifying a category whilst trying to esc out."
=> More closely match Sil 1.3's bane selection menu

src/mon-make.c
Resolves Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 , of Tevildo appearing without Oikeroi.
=> Unique friend placement: place friend rather than self

lib/gamedata/trap.txt, src/player-util.c
Also, better match trap names to the short and long descriptions.  Resolves https://github.com/NickMcConnell/NarSil/issues/392 .
=> Add punctuation for falling into a pit message.

src/player-attack.c
Matches Sil 1.3 behavior (there visibility check is built into message_pain()) and resolves https://github.com/NickMcConnell/NarSil/issues/398 .
=> On a player's ranged attack, only use monster pain message if out of sight

src/mon-move.c
Resolves https://github.com/NickMcConnell/NarSil/issues/399 and matches Sil 1.3's behavior.
=> Do not display a pass door message for monster going through an open door

.github/workflows/linux.yaml, .github/workflows/mac.yaml, .github/workflows/release.yaml, .github/workflows/windows.yaml
See GitHub's notice here, https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ , about the Node 16 to Node 20 transition.
=> Workflows: update versions of used actions for compatibility with Node 20

src/obj-make.c, src/ui-smith.c
Have ego_apply_magic() match Sil 1.3's behavior for the special bonus when the item is cursed or the special bonus does not matter.  When including the special bonus during smithing, replace the existing bonus regardless of sign.  Set the starting special bonus for a newly selected kind of object, new enchantment, or new artifact to match the default for that kind and enchantment.  Include the special bonus when deciding whether or not to enable the "Accept" entry.
Resolves https://github.com/NickMcConnell/NarSil/issues/357 .  Resolves https://github.com/NickMcConnell/NarSil/issues/397 .
=> Smithing: fix handling of special bonus

src/load.c, src/obj-init.c, src/obj-smith.c
Resolves https://github.com/NickMcConnell/NarSil/issues/415 .
Tolerate but warn if the number of artifacts in the save file is less than expected when reloaded.  As a bit of tolerance for modding, tolerate z_info->a_max being zero when a smithed artifact is created but skip using an artifact index of zero to agree with how artifact indices are used.
=> Have artifact count match up after reloading with smithed artifacts

src/ui-smith.c
Grey out categories that are not applicable to the current item.  If a greyd out category is selected, leave the artifice menu up rather than backing out to the top level smithing menu.
=> Smithing artifice: plug memory leaks and improve menu usability

lib/gamedata/object.txt, src/list-kind-flags.h, src/obj-util.c, src/obj-util.h, src/ui-smith.c
Use that for rings and amulets since Sil 1.3 does not use the base object's kind as the kind for the smithed object.  When resetting smithing objects for an artifact, do so before assigning the artifact field.  Resolves https://github.com/NickMcConnell/NarSil/issues/404 .
=> Introduce object kind flag to mark special kinds used for smithed artifacts

src/ui-smith.c
Leak happens if the enchant menu is entered when the base item (for instance a ring) does not allow any enchantments
=> Smithing: plug memory leak in enchant menu

lib/gamedata/monster_spell.txt
Previous version would reset the dice on the primary effect to -10.
=> SCARE: use -10 as the dice for noise side effect

src/effect-handler-general.c, src/mon-summon.c
1) Retry up to 1000 times to get the requested number summoned (see cmd1.c:2937-2971 in Sil 1.3).
2) Set vault argument to false when calling get_mon_num() (see monster2.c:3268 in Sil 1.3).
Resolves https://github.com/NickMcConnell/NarSil/issues/430 .
=> Better match Sil 1.3's summoning logic for roosts and webs

src/cmd-cave.c, src/ui-context.c
Affects attempts to open secret doors.  Resolves https://github.com/NickMcConnell/NarSil/issues/439 .  Fixes some messaging related to exchange places and leaping.  Prevents closed doors from being included in the disarming tests (unlike Vanilla Angband, Sil does not use "disarm" to lock an unlocked door) and allows disarming of glyphs of warding.
=> Restructure some tests using iscloseddoor, iswall, and isdisarmabletrap

src/cmd-cave.c
Resolves https://github.com/NickMcConnell/NarSil/issues/444 .  Adapted from Vanilla Angband's https://github.com/angband/angband/commit/bd273bad0f39ed88a1f095c048ba225ef8b05268 but with Sil's message.
=> Prevent using the mouse to close the door at the player's location

src/init.c
Avoids possibility of assertion failure/out-of-bounds write if a character dies on a larger level and then, without exiting, starts a new game or reloads anoter save with a smaller level size.
=> Forget field of fire when cleaning up

src/mon-move.c
See Sil 1.3's melee2.c:2299-2301.  May affect https://github.com/NickMcConnell/NarSil/issues/361 .
=> Match Sil 1.3 surrounding logic: diagonal from player with walls to east/west

src/mon-move.c
Better matches Sil 1.3 (see mon-move.c:2341-2372); previously would retreat if seen and could be fired on.  May affect https://github.com/NickMcConnell/NarSil/issues/361 .
=> When luring, retreat if seen or if can be fired on

src/mon-move.c
See Sil 1.3's melee2.c:1258-1259.  May affect https://github.com/NickMcConnell/NarSil/issues/361 .  Also replace "loc_diff(grid1, origin)" with the equivalent "actual" in the one place where the former was used.
=> Use coordinates in full cave when testing for escape routes

src/gen-room.c
That matches Sil 1.3 (see its generate.c:2798-2802,2890-2894,3033-3037), where the corners are for a simple room (just inside its bounding walls), and should make tunneling attempts more likely to suceed.  Change the solid_rock() tests for vaults to match Sil 1.3's behavior for interesting rooms and lesser vaults.
For greater vaults, Sil 1.3 uses (y1 - 5, x1 - 5, y2 + 5, x2 + 5) as the bounds for the solid_rock() test (see its generate.c:3022).  Do not use that here as Sil 1.3's behavior is not consistent with its own limits on where the vault is placed on the level and would lead to possible out-of-bounds accesses to the level's arrays.
=> Put stored corners for a vault just inside the vault's boundaries

src/wiz-stats.c, src/wizard.h
There are not two types of rubble like Vanilla Angband, so "pass_rubble" in the structure and "parubb" in the output file could be confusing.
=> Disconnection statistics: use "rubble" for grids with rubble

src/main-gcu.c, src/main-nds.c, src/main-sdl.c, src/main-sdl2.c, src/main-win.c, src/main-x11.c, src/main-xxx.c, src/ui-command.c, src/ui-map.c, src/ui-term.c, src/ui-term.h
On every platform, these were set to COLOUR_WHITE and ' ' respectively; replace them throughout with their manifest constants and remove them. It's not very obvious why they were originally added, since they were only used internally to Angband and never actually drawn on the screen - rather, any cell drawn with attr_blank and char_blank was considered empty and cleared in a platform-specific way. Making them configurable per-platform when in fact they were not exposed to the platform is somewhat puzzling.
=> ui-term: remove attr_blank & char_blank

docs/hacking/compiling.rst, src/Makefile.msys2.sdl2
* Get working sound with Makefile.msys2.sdl2; update the comments in that file.
* Change documentation about compiling the SDL2 front end under msys2 to add how to build with sound support and drop the mention of SDL2_gfx (that library isn't needed).
=> Get working sound with Makefile.msys2.sdl2; update the comments in that file. (#5492)

docs/hacking/compiling.rst
That's so the comments about --build and --host are closer to the example command; use i686-w64-mingw32 as the example for --build to match with recent Debian and Ubuntu releases
=> Docs: reorder Linux mingw cross-compiler instructions

src/main-win.c
Allow "Enable nice graphics" to use the full gamut of tile multipliers available in the menu; helps with https://github.com/angband/angband/issues/5500 (for some fonts will now choose a multiplier that allows the tiles to be displayed at their native resolution); also try to do more in the case of "Enable nice graphics" to preserve the aspect ratio of the tile if the tile is smaller than the font in one or more dimensions
=> Windows: tweak "Enable nice graphics"

configure.ac
Our source should be warnings-clean either way.
Fun side note here: since clang defines __GNUC__, autoconf detects clang as gcc and all the gcc-specific code (including this block) gets applied to clang too.
=> configure: remove --enable-more-gcc-warnings

configure.ac, src/h-basic.h, src/z-queue.h
The only C99 compiler (to my knowledge) that ever shipped without stdint.h was MSVC versions prior to Visual Studio 2010. Given the age of that compiler, we can probably drop support for it by now and just assume a proper C99 environment.
=> configure: remove stdint.h check

src/mon-init.c
Cherry-picked from Vanilla Angband's e3dd53200d001c97c3b4e2ff4a67299a24118c83 .
=> Avoid memory leak on parsing error for blow method's action string

src/savefile.c
May improve the error handling that led to this report, http://angband.oook.cz/forum/showpost.php?p=157868&postcount=38 , of a savefile failure.
=> Set character_saved to false if savefile could not be opened

src/Makefile.msys2.sdl2
libbrotli change was committted on 2021/10/6. Resolves https://github.com/angband/angband/issues/5303 .
=> SDL2: update MSYS2 compilation for upstream changes

src/main-sdl2.c
Resolves animal_waves report, http://angband.oook.cz/forum/showpost.php?p=157853&postcount=36 , of not being able to edit keymaps with the SDL2 front end.
=> SDL2: fix handling of '=' key

src/ui-game.c, src/ui-init.c
Call reinit_hook before textui_init() when restarting to mimic the normal start procedure in main.c and main-win.c. Resolves https://github.com/angband/angband/issues/4687 .
=> Always reload pref.prf when restarting

src/obj-make.c
Should also improve consistency with Sil 1.3 (see its object2.c:1860-1872 where there is one check against the artifact's level and none for the base object's level).
=> Port Vanilla Angband's removal of second level check for instant artifacts

docs/command.rst, docs/playing.rst, lib/help/a_comm.txt, lib/help/commands.txt
In at least one context, curses on Cygwin, control plus uppercase is not recognized.  The native Windows interface, native Mac interface, and the X11, curses, SDL, and SDL2 interfaces on Linux treat control + lowercase and control + uppercase the same.
=> Port Vanilla's document changes to use lowercase for control characters

acinclude.m4, configure.ac
* Fix up some typos when using the sdl-config arguments
* Don't query SDL CFLAGS and LIBS a second time
These variables are already set by `AM_PATH_SDL` and `AM_PATH_SDL2` and those actually include the SDL prefix that was set by the configure arguments.
=> Fix up handling of the SDL/SDL2 prefix when configuring (#5327)

lib/gamedata/terrain.txt, src/cave-square.c, src/cmd-cave.c, src/player-util.c
Also use square_apparent_look_prefix() more places and configure appropriate look strings for forges.
=> Port square_apparent_*() changes from Vanilla Angband

src/nds/nds-buttons.c, src/nds/nds-screenkeys.c, src/tests/z-util/util.c, src/z-util.c, src/z-util.h
* Add hex escape sequence for nds config files
Add an extra escape sequence, "\x", that can be used in "button-mappings.txt" and "screen-keys.txt" to encode arbitrary characters in the nds and 3ds port.
* Fix missing prototype warning
=> Add hex escape sequence for nds config files (#5394)

src/game-world.c
Avoids sequences of messages like, "You die.  You recover from the poisoning.".
=> Port Vanilla Angband's early returns on player death to damage over time

src/tests/object/util.c
The undefined behavior is applying an offset to a NULL pointer when object_prep() initializes an object's image_kind field.
=> Prevent object/util test case from triggering undefined behavior sanitizer

src/ui-event.h
Do not currently use it since do not have clashes for inscriptions or context menu shortcuts.  There are some overlaps when control is stripped (fuel a light source, ^f, with the fire commands, f and F; forge an item in the Angband-like keyset with Rogue-like navigation, ^d, and drop, d).  Those do not appear in the same context menus, and there's no useful object inscriptions targeting both of the commands involved in an overlap.
=> Port over Vanilla Angband's UN_KTRL_CAP

lib/gamedata/player_timed.txt, src/player-timed.c, src/player-timed.h, src/ui-display.c
Resolves https://github.com/NickMcConnell/NarSil/issues/547 .
In player_timed.txt, add a parameter to the change-grade directive to set the number of digits to use when formatting the current value of the timed effect.  If that number of digits is less than or equal to zero, only show the name without the current value for the timed effect.  Add a "Mortal wound" level for cuts:  Sil 1.3 and Sil-Q have it though it never is displayed (only triggers when the cut meter is greater than 100 but the cut meter is limited to 0 to 100).  That seems to be a bug in Sil 1.3 and Sil-Q so display the "Mortal wound" level when the cut meter is 100 or more.
In player_set_timed():
Cap the timed effect's value at the maximum for the effect's last change-grade.  That matches Sil 1.3's behavior where both …
=> Adjust handling of cuts and poisoning

src/init.c, src/trap.c
Tighten check for an invalid tval in flavor.txt's kind directive.  Use PARSE_ERROR_MISSING_RECORD_HEADER rather than assert() or no check at all if a directive is used outside of a record.  Avoid quit_fmt() when a parser error could be returned.  Avoid memory leaks on early returns due to errors or if some directives are repeated within a record.  Pair string_make() with string_free() rather than mem_free().  Use an unsigned int as the expected type of the parameter for name.txt's section directive since that's what's expected iternally.
=> Port Vanilla Angband's changes to init.c and parsing of trap.txt

src/cmd-wizard.c
Uses the same prequisites as are used elsewhere for adding a trap to a grid.  Also drop the restriction of no traps at a depth of zero since that is not relevant for NarSil.
=> Port Vanilla Angband's change to the debugging command for placing a trap

src/player-timed.c
Zero out pointer on cleanup.  Free before assignment to avoid leaking memory if a timed effect uses more than one change-dec directive.
=> player-timed: tighten lifecycle management for message set by change-dec

src/cocoa/snd-cocoa.m
Avoids a file descriptor leak seen with initWithContentsOfFile since macOS 10.15 (Catalina).
=> Mac: use NSSound's initWithData

lib/gamedata/constants.txt, src/cmd-wizard.c, src/init.c, src/init.h, src/obj-pile.c, src/player-calcs.c, src/tests/parse/body.c, src/tests/parse/f-info.c, src/tests/parse/flavor.c, src/tests/parse/h-info.c, src/tests/parse/house-info.c, src/tests/parse/names.c, src/tests/parse/p-info.c, src/tests/parse/partrap.c, src/tests/parse/sex-info.c, src/tests/parse/suite.mk, src/tests/parse/world.c, src/tests/parse/z-info.c, src/trap.c
Remove vestigial constants left over from Vanilla Angband.  Plug possibility of memory leaks if some directives in house.txt or sex.txt appear more than once in a record.
=> Port Vanilla Angband's changes for more test coverage of init.c and trap.c

src/ui-context.c, src/ui-output.c, src/ui-output.h, src/ui-term.c, src/ui-term.h
The artifacts seen were failures to clear or redraw when scrolling through the entries or if backing out one level of the menu and not at the top level of the menu.
=> Avoid drawing artifacts with the enter menu and big tiles

src/mon-init.c, src/tests/parse/lore.c
Port Vanilla Angband's changes to reenable test to parse monster.txt with the monster lore parser.
=> Get parsing of monster.txt as lore.txt to work.

src/ui-object.c
Was using floor_list's type, which is the same and will likely remain the same as floor_list's type.
=> Have allocation for throwing_list use its type

src/ui-effect.c
In the current code, the random option is always requested so the player will not see a change in how the menu behaves.
=> Effect selection menu: only add the random option if requested

src/Makefile.std
The former works with both GNU make and BSD make.  Fixes a regression introduced by 4.2.5:  on OpenBSD would have to use gmake rather than make to use Makefile.std (still have to change gcc to cc or clang, but that was also true with 4.2.4).
=> Makefile.std: use suffix rules rather than pattern rules

src/ui-input.c
1) Use get_com_ex() rather than get_com() so the argument for ^ is not coerced to a char. 2) Only use KTRL() to encode the keystroke if ENCODE_KTRL() for the argument to ^ is true; otherwise put KC_MOD_CONTROL in the modifiers.
Resolves https://github.com/angband/angband/issues/5748 .
=> Generalize handling of ^

src/Makefile, src/Makefile.src
That's to address part two of Magnate's request here, http://angband.oook.cz/forum/showpost.php?p=161423&postcount=1 .  Also use $(PROGNAME).o rather than angband.o in the clean rule so forks have one less thing to change.
=> Have "make clean" remove all optional intermediates

src/Makefile.osx
That would include files like .DS_Store or .deps that may have been generated in the source directory.
=> macOS: avoid cruft in the application bundle's lib/tiles directory

src/main-sdl2.c
Allows for better diagnostics if run from a desktop file or other situations where the user can not see what is written to standard error.
=> SDL2: display quit message to the screen

.github/workflows/linux.yaml, .github/workflows/release.yaml, .github/workflows/windows.yaml, configure.ac, docs/hacking/compiling.rst, src/h-basic.h
These typedefs aren't used anywhere in the source and it's hard to conceive of a situation where one would want to enable them, given that they have been fully replaced with standard C types.
=> configure: remove skip-old-int-typedefs option (#5524)

src/obj-init.c
Previous behavior for a misplaced directive would crash in one of those and trigger an assertion (if not a release build) in the other.  Both were missed in cff9ca2dc657deee5ead7897a29b01fb583e935b .
=> Object parsing: return "missing record header" error in two more places

CMakeLists.txt, docs/hacking/compiling.rst
Fixes building the documentation when cross-compiling for Windows on Unix and no version stamp file was present (build ID was not set in that case causing the rewritten conf.py for the manual to call version.sh; version.sh not availble at the expected relative path to the rewritten conf.py).
=> CMake: use version.sh to get build ID when the host is Unix

src/tests/run-tests
That happens on MSYS2 (mingw32 environment) running on Windows with test cases from a configure-based build using --enable-win (so using carriage return + line feed as line endings) while run-tests running within the MSYS2 environment expects Unix-style line endings.
=> run-tests: tolerate trailing carriage return on summary line from test

src/wiz-stats.c
Used wrong size for allocation (would be under the necessary size if sizeof(struct grid*) < sizeof(struct grid)) and would reallocate when there was still space for one more entry.
=> Correct reallocation used in the disconnection statistics command.

docs/command.rst, docs/playing.rst
That reflects the change in https://github.com/angband/angband/commit/afd45b56894440f89af75c4d8d15a2c793bc94fa and that there doesn't appear to be a compilation option to prevent the "double ctrl-z escape death trick".
=> Update docs about interrupt handling

.github/workflows/release.yaml
The typos weren't detrimental with the current form of Makefile.src.
=> Release workflow: fix typos in name extraction

.github/workflows/linux.yaml
Format argument checking is on for gcc and clang since 1168379ea574b476be28a8d2e3e7e69d7c1b2ed0 ; NarSil's CMakeLists.txt never implemented USE_PRINTF_STYLE_CHECKS .
=> Workflows: drop USE_PRINTF_STYLE_CHECKS for builds with CMake

docs/hacking/compiling.rst
Also note that "make install" is necessary with the SHARED_INSTALL or READONLY_INSTALL options to CMake.
=> Compiling docs: replace angband with narsil; clarify when autogen.sh needed

configure.ac
Makefiles and the game do not use those, but some test cases do.  Allows the test cases using set_file_paths() to work on Windows from builds using configure.
=> configure: change default configpath/libpath/varpath for Windows

src/main.c
That's a post 1.3.0 regression introduced by 6d51d768833043dc198a9f8944ca7b324617af78 .
=> Avoid possible use after free when "-l" option fails

src/score.c
Address the crashing part of https://github.com/angband/angband/issues/6022 but not whatever caused openng the locking file to fail.
=> Avoid crash when locking file for high scores could not be opened

src/main-win.c
See https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170 .  Also, if either is already set, undefine first in case the compiler issues a warning for redefining a macro to a different value.
=> Windows: set both WINVER and _WIN32_WINNT to enforce minimum version

src/player-util.c
Do it before the "Die? " prompt so it is accessible to the EVENT_CHEAT_DEATH handlers or something looking for the "Die? " prompt.
=> Port Vanilla Angband's change to note the cause of death earlier

src/main-sdl2.c
Resolves part of Ituirth's report here, https://angband.live/forums/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248346#post248346 , of problems with two entries in tangar's font.
=> SDL2: map 127 to whatever the font has rather than a space

src/tests/parse/parse.c
Avoids compiler warnings with MSVC.
=> Fix wchar_t assignment to char in a test case

src/mon-init.c, src/tests/parse/r-info.c
Those are the last three that would access a NULL pointer for a misplaced directive rather than signal a parsing error on a specific line.
=> monster.txt: return missing record header for misplaced base, glyph, blow

configure.ac
Replace instances of '==' with '=' when used with the test command line utility. '==' is not documented and might lead to portability problems.  Put the logic for the spoiler, statistics, and test front ends before the logic for the Windows front end so the resetting of MAINFILES by the Windows front end has its full intended effect.
=> Clean up configure a little

CMakeLists.txt, docs/hacking/modifying.rst, lib/gamedata/Makefile, lib/gamedata/ui_knowledge.txt, src/tests/parse/suite.mk, src/tests/parse/ui_knowledge.c, src/ui-init.c, src/ui-knowledge.c, src/ui-knowledge.h, src/win/vs2019/Angband.vcxproj, src/win/vs2019/Angband.vcxproj.filters
Now configured via lib/gamedata/ui_knowledge.txt rather than hardwired categories in src/ui-knowledge.c.  The ordering of hallucinatory monsters in the categories will likely be different than before:  they'll appear last, after any non-hallucinatory monsters in the category.
=> Port Vanilla Angband's changes for configuring monster knowledge categories

src/cmd-core.c, src/cmd-core.h, src/cmd-obj.c, src/init.c, src/player-birth.c
The lifetime of string argument for a command submitted to the queue is now managed by the queue.  Prevents a use after free if the last command is repeated immediately after inscribing an object.  Also change how the queue handles requests to repeat the last command.  Have it remember the possible target for repetition rather than searching through the queue for it.
=> Port Vanilla Angband's changes to command queue string management

src/player-path.c
Ported from Vanilla Angband.  Done so "repeat last" will try to repeat the pathfinding command rather than the last run step that the pathfinding command executed.
=> Mark the run commands used to implement pathfinding as background commands

src/player-timed.c
Resolves https://github.com/NickMcConnell/NarSil/issues/692.  Also have the result of player_inc_check(player, TMD_AFRAID, ...) be the same regardless of the lore parameter when the player is subject to TMD_RAGE.
=> Have player_inc_check() use known state for lore checks

src/ui-combat.c, src/ui-combat.h
Resolves the sixth part of https://github.com/NickMcConnell/NarSil/issues/735 .
=> Use wchar_t to store glyphs for the attacker/defender in combat rolls

src/generate.c
Resolves second part of https://github.com/NickMcConnell/NarSil/issues/735 .
=> Check for overflow of uint8_t in vault parsing

src/ui-prefs.c
Resolves https://github.com/angband/angband/issues/6127 .
=> Avoid coercing a trap's character to a char when parsing preferences

src/main-cocoa.m
Seen with NarSil when changing between Adam Bolt's tiles and the old tiles with the tile size set to 200%.
=> macOS: avoid triggering the undefined behavior sanitizer on tile switch

src/obj-smith.c
Has no effect in an unmodded game since the mithril corslet, with a weight of 150, is the heaviest mithril item.  Resolves the fifth part of https://github.com/NickMcConnell/NarSil/issues/735 .  Also correct the calculation of the slots needed for melting when the item's weight is a multiple of mithril's maximum stack size, 99.
=> Restructure mithril melting to tolerate weights greater than 255

src/obj-util.h
It is no longer present and was replaced by object_is_known_artifact() in obj-knowledge.{c,h}.
=> Remove declaration for obj_is_known_artifact()

src/obj-slays.c
1.  Do not learn monster flags on attacks when there is not a relevant brand or slay.
2.  If the monster resists a brand, do not learn about the vulnerable flag, if the brand has one, since the damage is not affected by whether the monster has the vulnerable flag in that case.
3.  Tolerate brands which do not have a resist flag.
Resolves https://github.com/NickMcConnell/NarSil/issues/757 .
=> Tweak learning of brands and slays

src/obj-slays.c
The removed checks on "learn" are redundant after a7dd12f30f880042e72caf43ece205c74998fe09 .
=> Simplify some tests when learning brands/slays

src/mon-lore.c
Resolves https://github.com/NickMcConnell/NarSil/issues/764 .
=> Correct writing lore when there is more than one known drop (1.3 branch)

src/obj-smith.c, src/ui-smith.c
When smithed object is accepted, copy the known version into dynamically allocated memory so that later cleanup does not try to deallocated statically allocated memory.  Resolves the crash reported on 2024/11/5 for https://github.com/NickMcConnell/NarSil/issues/728 .
=> Smithing: have known version in special_display() and artefact_display()

src/obj-smith.c
Prevents future smithing attempts before a save and reload from affecting the obect.  Resolves https://github.com/NickMcConnell/NarSil/issues/769 .
=> Point object for accepted smithed artifact to the artifact's permanent record

src/obj-smith.c
Prevents future smithing attempts before a save and reload from affecting the obect. Resolves #769 .
=> Point object for accepted smithed artifact to artifact's permanent record (1.3)

src/cave-map.c, src/cave.h, src/obj-init.c, src/object.h, src/ui-map.c, src/ui-obj-list.c, src/ui-object.c
Resolves https://github.com/NickMcConnell/NarSil/issues/563 .
=> Allow non-instant artifact colors without inteference for other objects (1.3 branch)

src/cave-map.c, src/cave.h, src/obj-init.c, src/object.h, src/ui-map.c, src/ui-obj-list.c, src/ui-object.c
Resolves https://github.com/NickMcConnell/NarSil/issues/563 .
=> Allow non-instant artifact colors without inteference for other objects

CMakeLists.txt, lib/user/archive/.gitignore, src/main-win.c
Also ensures lib/user/archive is set up for self-contained installs via CMake.
=> Ensure archive directory presence if running Windows front end in place

CMakeLists.txt, lib/user/archive/.gitignore, src/main-win.c
Also ensures lib/user/archive is set up for self-contained installs via CMake.
=> Ensure archive directory presence if running Windows front end in place (1.3 branch)

src/ui-smith.c
Related to https://github.com/NickMcConnell/NarSil/issues/728 .
=> Avoid smithing crash (address sanitizer; only numbers modified for base object)

src/cave-fire.c, src/cmd-cave.c, src/generate.c, src/player-util.c, src/project-feat.c
Affects bashing doors, altering terrain, confirmations for moving/leaping into a hazardous situation, searching, and describing the results of a horn of blasting.
=> Replace most square_ismark() calls with square_isknown() or square_isseen()

docs/customize.rst, docs/playing.rst
Also clean up references to the "roguelike keyset".  Resolves https://github.com/NickMcConnell/NarSil/issues/603 .
=> Docs: mention 'O' as a way to bring up the options menu

docs/customize.rst, docs/playing.rst
Also clean up references to the "roguelike keyset".  Resolves https://github.com/NickMcConnell/NarSil/issues/603 .
=> Docs: mention 'O' as a way to bring up the options menu (1.3 branch)

src/cave-map.c, src/cave-view.c, src/player-calcs.c, src/player-calcs.h
Return early if the weapon has no slays and break out of the viewable calculation early once the weapon is known to be viewable.
=> Make weapon_glows() a bit more efficient

src/cave-map.c, src/cave-view.c, src/player-calcs.c, src/player-calcs.h
Return early if the weapon has no slays and break out of the viewable calculation early once the weapon is known to be viewable.
=> Make weapon_glows() a bit more efficient - 1.3 branch

lib/tiles/microchasm/graf-mcm.prf, src/main-cocoa.m, src/main-sdl.c, src/main-sdl2.c, src/main-win.c, src/ui-map.c, src/ui-prefs.c, src/ui-prefs.h, src/z-color.h
Resolves the second part of https://github.com/NickMcConnell/NarSil/issues/608 .  For other tile sets which support transparency, would need to add tiles for the glow and alert indicators and then reference those tiles in the preference file.  The current implementation assumes that no double-height tile will get the glow indicator.  If that assumption is wrong, would need to allow for both single-height and double-height glow indicators in ui-prefs.c and change the rendering logic to support a double-height glow indicator.
=> Microchasm's tiles: support the alert and glow indicators

lib/tiles/microchasm/graf-mcm.prf, src/main-cocoa.m, src/main-sdl.c, src/main-sdl2.c, src/main-win.c, src/ui-map.c, src/ui-prefs.c, src/ui-prefs.h, src/z-color.h
Resolves the second part of https://github.com/NickMcConnell/NarSil/issues/608 .  For other tile sets which support transparency, would need to add tiles for the glow and alert indicators and then reference those tiles in the preference file.  The current implementation assumes that no double-height tile will get the glow indicator.  If that assumption is wrong, would need to allow for both single-height and double-height glow indicators in ui-prefs.c and change the rendering logic to support a double-height glow indicator.
=> Microchasm's tiles: support the alert and glow indicators - 1.3 branch

src/ui-map.c, src/ui-tutorial.c
Fixes a regression introduced in 1.3.1 by e6a711707bd0057bd9a1a3b9b18bfa58d594e04a .  Also corrects display of wall characters in tutorial textblocks and, for terrain while raged, extracts the background color like the frontends do.
=> Get highlight_unwary option to work again - 1.3 branch

src/mon-blows.c
The handling of dark resistance is for future-proofing: no equipment currenly provides dark resistance but mon-attack.c's elem_bonus() already checks for it.
=> Learn equipment's poison/dark resistance from monsters' melee - 1.3 branch

src/mon-blows.c
Resolves https://github.com/NickMcConnell/NarSil/issues/817 .  The handling of dark resistance is for future-proofing:  no equipment currenly provides dark resistance but mon-attack.c's elem_bonus() already checks for it.
=> Learn about equipment's poison/dark resistance from monsters' melee attacks

src/ui-map.c, src/ui-tutorial.c
Fixes a regression introduced in 1.4.0 by e6a711707bd0057bd9a1a3b9b18bfa58d594e04a .  Also corrects display of wall characters in tutorial textblocks and, for terrain while raged, extracts the background color like the frontends do.
=> Get highlight_unwary option to work again

src/object.h
That is for consistency:  all other fields have initializers.  Should have no effect in practice since the compiler should set to zero any fields in a static structure variable that were not explicitly initialized.
=> Initialize pseudo in OBJECT_NULL - 1.3 branch

src/obj-smith.c, src/ui-smith.c
Set up known version of mithril stack before giving it to the player.  Alloocate the right amount of space for the menu information if there is more than one mithril item available to melt.  Related to https://github.com/NickMcConnell/NarSil/issues/728 .
=> Fix two issues with melting mithril items

src/obj-info.c
Examples of those include DIG_1, TWO_HANDED, and HAND_AND_A_HALF.  Resolves https://github.com/NickMcConnell/NarSil/issues/827 .
=> In object descriptions, skip miscellaneous properties without flavor text

src/obj-info.c
Examples of those include DIG_1, TWO_HANDED, and HAND_AND_A_HALF.
=> In object descriptions, skip miscellaneous properties without flavor text - 1.3

src/obj-smith.c
1) Account for a mithril stack in the pack that might combine with the result of melting the item.
2) Use the max_stack relevant for pieces of mithril.  Prior calculation used a mix of max_stack for the item to melt and max_stack for pieces of mithril.  No effect currently as max_stack is the same for both.
=> Tweak needed slots calculation for melting mithril item - 1.3

src/obj-info.c
Resolves https://github.com/NickMcConnell/NarSil/issues/848 .
=> For object information, skip protections in describe_misc_magic()

src/obj-info.c, src/obj-smith.c, src/obj-smith.h, src/ui-smith.c
The tweaks for object information are:  check for OINFO_SMITH or OINFO_SPOIL in more cases when making the decision to use the fully or partially known values; make OINFO_TERSE orthogonal to OINFO_EGO (and with this change OINFO_SMITH and OINFO_SPOIL) for excluding the kind's base flags from those for the object, use the flags determined by get_known_flags() when describing a light rather than obj->flags, and include the effect of OF_LIGHT when displaying the radius for a light.
Resolves https://github.com/NickMcConnell/NarSil/issues/852 for the 1.3 branch.
=> Decouple light radius from special bonus when smithing; tweak object info - 1.3

src/ui-object.c
There would only be a leak if the kind specified slays, brands, or an ability list.  In the current game, no kinds do so.
=> Plug potential memory leak in 1.3 branch's display_object_kind_recall()

lib/gamedata/object.txt, lib/gamedata/object_property.txt, src/obj-init.c, src/obj-make.c, src/obj-make.h, src/obj-properties.h, src/obj-smith.c, src/player-birth.c, src/ui-smith.c
In the unmodded game, the noticeable differences are for smithing artifact shovels, mattocks, or shadow cloaks, smithing ego shadow cloaks, or ego shadow cloaks from dungeoon generation or monster drops.  Resolves https://github.com/NickMcConnell/NarSil/issues/851.  Corrects mismatches with Sil 1.3 for smithed artifact shadow cloaks, shovels, and mattocks that https://github.com/NickMcConnell/NarSil/commit/a7caa79e71d4591b7fe739bce99c609f7282aef6 does not.
Shovels and mattocks now use the tunneling modifier for their base digging bonus rather than the DIG_1 or DIG_2 flags.  That introduces an annoyance for games started before the change:  unless the character has wielded something with a tunneling modifier or smithed something with a tunneling modifier, even standard shovels and mattocks …
=> Better mimic Sil 1.3 egos/smithing for base objects with modifiers

lib/gamedata/brand.txt, lib/gamedata/slay.txt, src/obj-init.c, src/object.h, src/tests/parse/brand.c, src/tests/parse/slay.c
All the smithing data for properties comes from object_property.txt.
=> Remove unused smithing difficulties from slay.txt and brand.txt

lib/gamedata/brand.txt, lib/gamedata/slay.txt, src/obj-init.c, src/object.h, src/tests/parse/brand.c, src/tests/parse/slay.c
All the smithing data for properties comes from object_property.txt.
=> Remove unused smithing difficulties from slay.txt and brand.txt - 1.3

src/obj-smith.c
See cmd4.c:2699,2703,2718 in Sil 1.3.  Resolves https://github.com/NickMcConnell/NarSil/issues/861 .
=> Mimic Sil:  cost is zero, not negative, for a negative modifier

src/obj-smith.c
See cmd4.c:2699,2703,2718 in Sil 1.3.  Resolves https://github.com/NickMcConnell/NarSil/issues/861 for the 1.3 branch.
=> Mimic Sil: cost is zero, not negative, for a negative modifier - 1.3

src/obj-info.c
Incorrect size was introduced in aef812406ce42cbcfec139123378a601acccc28c .  Resolves https://github.com/NickMcConnell/NarSil/issues/869 .
=> Correct array size in obj_known_light() declaration

src/obj-info.c
Incorrect size was introduced in 6320d461b939cf2087bebbfa8333f3265cae45e7 .  Resolves https://github.com/NickMcConnell/NarSil/issues/869 for the 1.3 branch.
=> Correct array size in obj_known_light() declaration - 1.3

lib/gamedata/object.txt, lib/gamedata/object_property.txt, src/obj-init.c, src/obj-make.c, src/obj-make.h, src/obj-properties.h, src/obj-smith.c, src/ui-smith.c
In the unmodded game, the noticeable differences are for smithing artifact shovels, mattocks, or shadow cloaks, smithing ego shadow cloaks, or ego shadow cloaks from dungeoon generation or monster drops.  Resolves https://github.com/NickMcConnell/NarSil/issues/851 for the 1.3 branch.  Corrects mismatches with Sil 1.3 for smithed artifact shadow cloaks, shovels, and mattocks that https://github.com/NickMcConnell/NarSil/commit/a7caa79e71d4591b7fe739bce99c609f7282aef6 does not.
Shovels and mattocks now use the tunneling modifier for their base digging bonus rather than the DIG_1 or DIG_2 flags.
=> Better mimic Sil 1.3 egos/smithing for base objects with modifiers - 1.3

src/tutorial.c, src/ui-object.c
For kind recall, mark the item as known in the same circumstances as the knowledge menu does.  With https://github.com/NickMcConnell/NarSil/pull/872 also in place for the 1.3 branch, causes the tunneling bonus for shovels and mattocks to be shown in kind recall and allows the tunneling bonus for the tutorial's shovel to be seen without first wielding it.  That better emulates what Sil 1.3 does.
=> Mark ordinary weapons and armour as known in the tutorial - 1.3

src/ui-tutorial.c
Also plug memory leaks for the known versions of objects if the tutorial purges the default starting kit or can not fit an item from the starting kit in the pack.  Changes have no effect on the unmodded game as the tutorial currently does not modify the default starting kit for the player.
=> In the tutorial, set up known version of starting kit as normal birth does

src/obj-gear.c
See inven_damage() and damage_armour() in Sil 1.3's spells1.c.
=> Exempt quiver slots from acid damage like Sil 1.3 does

src/mon-blows.c
See melee1.c:1081-1096 and spells1.c:998-1013 in Sil 1.3.  May explain Infinitum's comments about acid damage to equipment here, https://angband.live/forums/forum/angband/sil/10693-narsil-1-3-0?p=228499#post228499 .  For an elemental blow, skip identifying the element or applying object damage when the player died to the blow.
=> Have acidic blows affect equipped armour as in Sil 1.3

src/mon-blows.c
See melee1.c:1081-1096 and spells1.c:998-1013 in Sil 1.3.  May explain Infinitum's comments about acid damage to equipment here, https://angband.live/forums/forum/angband/sil/10693-narsil-1-3-0?p=228499#post228499 .  For an elemental blow, skip identifying the element or applying object damage when the player died to the blow.
=> Have acidic blows affect equipped armour as in Sil 1.3 - 1.3

src/tests/parse/objbase.c
Better matches up with what's done in other error messages.
=> In objbase parsing tests, add colons to error messages

src/savefile.c, src/tests/unit-test-data.h, src/z-dice.c
The text of such warnings begins with "warning: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' a ttribute".  Those warnings are controlled by the -Wunterminated-string-initializ ation option.
=> Avoid warnings on msys2 about truncation when initializing array from string

docs/customize.rst
Resolves https://github.com/angband/angband/issues/6243 .  Also describe how that window<->subwindow relationship is managed.
=> Fix missing word in the documentation about configuring SDL2 - 1.3 branch

src/ui-game.c
That is necessary for correct operation with setgid installations.
=> Use extra privileges for existence check in savefile_name_already_used()

.gitignore, src/doc/doxygen-mainpage.md, src/doc/doxygen.conf
Port Jordan Philyaw's changes to Vanilla to reenable doxygen.  His comments at https://github.com/angband/angband/pull/6292 apply for NarSil as well.  Namely, use "doxygen src/doc/doxygen.conf" from the top level directory to build the documentation in src/doc/_doxygen .
=> doxygen conf updates to get building. mainpage md. gitignore build dir

.gitignore, src/doc/doxygen-mainpage.md, src/doc/doxygen.conf
Port Jordan Philyaw's changes to Vanilla to reenable doxygen.  His comments at https://github.com/angband/angband/pull/6292 apply for NarSil as well.  Namely, use "doxygen src/doc/doxygen.conf" from the top level directory to build the documentation in src/doc/_doxygen .
=> doxygen conf updates to get building. mainpage md. gitignore build dir - 1.3

src/player-attack.c
Affects messaging for melee with sharp or vampiric weapons (though only when the rune is learned, and vampiric weapons are currently learn on wield) and for thrown or launched attacks with sharp weapons.
=> Correct lengths passed to flag_slay_message()

src/cocoa/AppDelegate.m, src/main.c, src/parser.c
The comments used <something> to refer to some text whose specific contents were not specified.  doxygen tried to interpret those as HTML links.  Using backticks rather than angle brackets satisfies doxygen and hopefully does not confuse other readers.
=> Replace <something> with `something` where it confused doxygen

src/cocoa/AppDelegate.m, src/main.c, src/parser.c
The comments used <something> to refer to some text whose specific contents were not specified.  doxygen tried to interpret those as HTML links.  Using backticks rather than angle brackets satisfies doxygen and hopefully does not confuse other readers.
=> Replace <something> with `something` where it confused doxygen - 1.3

src/project-mon.c
Resolves https://github.com/NickMcConnell/NarSil/issues/919 .
=> Correct damage rolls for projections affecting monsters - 1.3

docs/hacking/compiling.rst
Relabel 'Documentation' as 'User Documentation' and include in it how to build the user manual when using configure or CMake.  Add a section, 'Developer Documentation' and specify how to run doxygen there.
=> docs: rework the section on how to compile the documentation

src/ui-effect.c, src/ui-input.c, src/ui-menu.c, src/ui-menu.h, src/ui-object.c, src/ui-target.c, src/ui-target.h
Only recognize a keymap trigger if its action is one walk or run command.  Also, depending on the context, allow a keymap trigger whose first key in the action is ESCAPE to break out of the selection process.  The latter resolves https://github.com/angband/angband/issues/6297 .  Such a keymap trigger can also break out of item or effect selection.  They do not affect retrieving the input when the player is prompted for a string, quantity, confirmation, or single character.  Menus used in the knowledge or preferences menu are not affected unless they use the item/effect input methods.
=> Rework how keymaps are handled when extracting a direction - 1.3

src/obj-properties.c, src/ui-tutorial.c
Instances that are not known to be triggerable in the current code but were chaged to be more robust:
1. Issue an appropriate message rather than crash if flag_slay_message() is called with an invalid flag or the flag was not configure in object_property.txt.
2. Issue an appropriate message rather than crash if element_message() is called with an invalid element or the resistance/vulnerability to that element was not configured in object_property.txt.
Also unroll one iteration for random selections in ui-tutorial.c to avoid some false positives from the static analysis.
=> Adjust some code flagged by gcc's static analysis option, -fanalyzer

src/obj-properties.c, src/ui-tutorial.c
Instances that are not known to be triggerable in the current code but were chaged to be more robust:
1. Issue an appropriate message rather than crash if flag_slay_message() is called with an invalid flag or the flag was not configure in object_property.txt.
2. Issue an appropriate message rather than crash if element_message() is called with an invalid element or the resistance/vulnerability to that element was not configured in object_property.txt.
Also unroll one iteration for random selections in ui-tutorial.c to avoid some false positives from the static analysis.
=> Adjust some code flagged by gcc's static analysis option, -fanalyzer - 1.3

docs/hacking/compiling.rst
Old text has multiple "not" statements, and is confusing to the reader.
=> Clarify confusing text in compiling.rst

docs/hacking/compiling.rst
Old text has multiple "not" statements, and is confusing to the reader.
=> Clarify confusing text in compiling.rst - 1.3
